# Generated by Django 3.2.8 on 2021-12-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_clinics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinics',
            old_name='clinical_officer_id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='clinics',
            name='transfer_request',
            field=models.BooleanField(default=False),
        ),
    ]
