# Generated by Django 3.2.8 on 2021-12-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211202_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinics',
            name='accept_transfer_request',
            field=models.BooleanField(default=False),
        ),
    ]
