# Generated by Django 3.2.8 on 2021-12-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_clinic_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinic_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
