# Generated by Django 3.2.8 on 2021-11-19 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_type', models.CharField(max_length=255)),
                ('drug_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DrugsInSTock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_qty', models.IntegerField()),
                ('final_qty', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drugs')),
            ],
        ),
        migrations.CreateModel(
            name='DrugShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_date', models.DateTimeField()),
                ('expected_arrival_time', models.DateTimeField()),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drugs')),
            ],
        ),
        migrations.CreateModel(
            name='DrugAvailableLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drugs')),
            ],
        ),
    ]
