# Generated by Django 3.2.8 on 2021-11-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugavailablelocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='drugavailablelocation',
            name='longitude',
        ),
    ]
